### ISSUE TITLE
Does it make you feel good reuploading old src leaks for clout? Does it give you that egotistical vision which makes it look like you can actually code shit? You say you expose skids but your entire github is for your ego boost.

### ISSUE THREAD

**Issue by Napoleon-ZoomberParts** [PaceCodes/StrikePractice#1]
clout chaser

**Comment by Napoleon-ZoomberParts** [comment]
also, btw I dont dev any of the shit on here or whatever this skid plugin is idfk, I am just a passer by

**Comment by Napoleon-ZoomberParts** [comment]
Lmao ok, just got some pics about how you used to be a Jartex admin lmaooooooo 
I bet you dont even own minecraft, need the extra ego because of the funne that happened?

**Comment by PaceCodes** [comment]
Sure lmao cry harder kiddie. And I'm not the jartex admin there are a lot of pace in community but eww skid don't have a brain, and how is that a 're-upload' src leak?
